
[cursor]
blink_interval = 500
thickness = 0.1
unfocused_hollow = true

[cursor.style]
blinking = "always"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 20.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false
dynamic_title = true
opacity = 0.75
title = "Najee89b - Alacritty"

[colors]
draw_bold_text_with_bright_colors = true

[general]
live_config_reload = true
